#!/usr/bin/env node
// WHAT IS ALREADY HERE. Generates tools/INDEX.md from the tools themselves.
//
//   node tools/m59-index.mjs           # write tools/INDEX.md
//   node tools/m59-index.mjs --check   # exit 1 if INDEX.md is stale (for CI)
//   node tools/m59-index.mjs --find shop   # search names and summaries
//
// WHY THIS EXISTS. This directory went from 151 tools to 589 in twenty-four days with no index,
// and the cost is not disk — it is that nobody can answer "does this already exist?" so they
// write it again. Two of the five findings in the 2026-09-05 operations review were literally
// "this already exists and nobody can see it": m59-status.mjs, and m59-fleet-repl.mjs, which had
// been rescued off the prod-deploy branch the day before and referenced in CLAUDE.md zero times.
//
// The metadata was never missing. Every tool already opens with a header comment saying what it
// is. This just collects them. That is the whole idea: the index is DERIVED, so it cannot drift
// the way a hand-maintained list does, and regenerating it is cheaper than reading the directory.
//
// A tool with no header comment shows up as NO SUMMARY. That is a prompt to write one, not a bug.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const TOOLS = dirname(fileURLToPath(import.meta.url));
const INDEX = join(TOOLS, 'INDEX.md');

// The first prose line of the header, with the noise the repo happens to use stripped off.
function summarize(file) {
  let text;
  try {
    text = readFileSync(join(TOOLS, file), 'utf8');
  } catch {
    return null;
  }
  const lines = text.split(/\r?\n/, 40);
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#!')) continue;
    if (!line.startsWith('//')) break;          // header block is over
    let s = line.replace(/^\/\/\s?/, '').trim();
    if (!s) continue;
    // "m59-decide.mjs -- THE DECIDE HALF" -> "THE DECIDE HALF"
    s = s.replace(/^m59-[\w-]+\.mjs\s*[-—:]+\s*/i, '');
    if (!s) continue;
    return s.replace(/\s+/g, ' ');
  }
  return null;
}

function collect() {
  const files = readdirSync(TOOLS).filter((f) => f.endsWith('.mjs') && f !== 'm59-index.mjs');
  const rows = files.sort().map((f) => ({
    file: f,
    name: f.replace(/^m59-/, '').replace(/\.mjs$/, ''),
    test: /-test\.mjs$/.test(f),
    summary: summarize(f),
  }));
  return rows;
}

function render(rows) {
  const tools = rows.filter((r) => !r.test);
  const tests = rows.filter((r) => r.test);
  const missing = tools.filter((r) => !r.summary).length;
  const out = [];
  out.push('# tools/ index');
  out.push('');
  out.push('**Generated by `node tools/m59-index.mjs`. Do not edit by hand.**');
  out.push('');
  out.push(`${tools.length} tools, ${tests.length} tests.` +
    (missing ? ` ${missing} tool(s) have no header comment.` : ''));
  out.push('');
  out.push('Read this before writing a new tool. `node tools/m59-index.mjs --find <word>`');
  out.push('searches it. If what you need is here, use it; if it is nearly here, extend it.');
  out.push('');
  out.push('## Tools');
  out.push('');
  out.push('| Tool | What it is |');
  out.push('|---|---|');
  for (const r of tools) {
    const s = (r.summary || '**NO SUMMARY — add a header comment**').replace(/\|/g, '\\|');
    out.push(`| \`${r.name}\` | ${s} |`);
  }
  out.push('');
  out.push('## Tests');
  out.push('');
  out.push(tests.map((r) => `\`${r.name}\``).join(', '));
  out.push('');
  return out.join('\n');
}

const rows = collect();
const body = render(rows);

if (process.argv.includes('--find')) {
  const term = (process.argv[process.argv.indexOf('--find') + 1] || '').toLowerCase();
  if (!term) {
    console.error('--find needs a word');
    process.exit(2);
  }
  const hits = rows.filter(
    (r) => r.name.toLowerCase().includes(term) ||
      (r.summary || '').toLowerCase().includes(term),
  );
  for (const r of hits) console.log(`${r.name.padEnd(28)} ${r.summary || '(no summary)'}`);
  console.log(`\n${hits.length} of ${rows.length} tools match "${term}"`);
  process.exit(0);
}

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(INDEX, 'utf8');
  } catch { /* missing counts as stale */ }
  if (current.trim() !== body.trim()) {
    console.error('tools/INDEX.md is stale — run: node tools/m59-index.mjs');
    process.exit(1);
  }
  console.log('tools/INDEX.md is current');
  process.exit(0);
}

writeFileSync(INDEX, body + '\n');
const tools = rows.filter((r) => !r.test).length;
const missing = rows.filter((r) => !r.test && !r.summary).length;
console.log(`tools/INDEX.md: ${tools} tools, ${rows.length - tools} tests` +
  (missing ? `, ${missing} missing a header comment` : ''));
